### ISSUE TITLE
link for raw data example is unvalid

### ISSUE THREAD

**Issue by laudcock** [ecekt/eyegaze#6]
Hi

The link to the raw data example is unvalid:  https://github.com/mani-tajaddini/The-Group-Eye-Tracking-Project/tree/master/Lottary%20Experiment-raw. Can you update the link? 

Greetings 
Laure

**Comment by ecekt** [comment]
Hi Laure,

Unfortunately, I was not maintaining that link and I don't have access to the dataset now. You can either ask [Mani](https://github.com/mani-tajaddini) if he still has the dataset or I may help you modify my code so that you can use it with your own dataset.

Best

**Comment by laudcock** [comment]
Hey, I managed to import my data, thanks for your reply!
