### ISSUE TITLE
example

### ISSUE THREAD

**Issue by JGoeke** [ecekt/eyegaze#7]
Hi, I want to use that code to get the number of fixations and the duration but I did not find any example how tha raw data should look like. Can you provide me an example for that? 

Best Regards

**Comment by ecekt** [comment]
Hi, unfortunately, I don't have the data anymore, but if you take a look at [gaze.py](https://github.com/ecekt/eyegaze/blob/master/gaze.py), you'll see that I list what the columns correspond to in the csv file I had. Of course, your data could be different: maybe you only have the timestamp, x and y coordinates. I think the ivt and idt functions would work with only those. However, you may need to adapt some other code according to your own data. I seem to have an artificial dataset [here](https://github.com/ecekt/eyegaze/blob/master/artificial_group.csv), but note that it includes gaze from a group of subjects. Let me know if you have further questions!
